import { NgModule } from '@angular/core';
import { NbIconLibraries } from '@nebular/theme';
import {
	IconActivity,
	IconAlertCircle,
	IconAlertTriangle,
	IconChevronLeft,
	IconChevronRight,
	IconArchive,
	IconArrowLeft,
	IconArrowUp,
	IconArrowUpCircle,
	IconArrowDown,
	IconArrowRight,
	IconAt,
	IconPaperclip,
	IconAward,
	IconChartBar,
	IconBell,
	IconBook,
	IconBriefcase,
	IconBrowser,
	IconBulb,
	IconCalendar,
	IconCamera,
	IconCar,
	IconCast,
	IconCreditCard,
	IconCircleCheck,
	IconCheck,
	IconSquareCheck,
	IconChevronDown,
	IconChevronUp,
	IconClock,
	IconX,
	IconCircleX,
	IconSquareX,
	IconCloudDownload,
	IconCloudUpload,
	IconCode,
	IconSettings,
	IconArrowsMinimize,
	IconPalette,
	IconCompass,
	IconCopy,
	IconCornerDownRight,
	IconCpu,
	IconCube,
	IconArrowUpRight,
	IconChecks,
	IconDownload,
	IconEdit,
	IconMail,
	IconMaximize,
	IconExternalLink,
	IconEye,
	IconEyeOff,
	IconBrandFacebook,
	IconFile,
	IconFilePlus,
	IconFileText,
	IconMovie,
	IconFlag,
	IconBolt,
	IconRotate2,
	IconFolder,
	IconFolderPlus,
	IconFilter,
	IconGift,
	IconGitBranch,
	IconGitCommit,
	IconBrandGithub,
	IconGlobe,
	IconBrandGoogle,
	IconGridDots,
	IconBrandWindowsFilled,
	IconServer,
	IconHash,
	IconHeart,
	IconHome,
	IconPhoto,
	IconPhotoOff,
	IconInbox,
	IconInfoCircle,
	IconKeyboard,
	IconStack2,
	IconLayout,
	IconLink,
	IconBrandLinkedin,
	IconList,
	IconLoader,
	IconLock,
	IconLockOpen,
	IconLogin,
	IconLogout,
	IconMap,
	IconMenu2,
	IconMenuOrder,
	IconMessageCircle,
	IconMessage,
	IconMicrophone,
	IconMinus,
	IconCircleMinus,
	IconSquareMinus,
	IconDeviceDesktop,
	IconMoon,
	IconDots,
	IconDotsVertical,
	IconArrowsMove,
	IconNavigation,
	IconBrandNpm,
	IconAdjustmentsHorizontal,
	IconSend,
	IconPlayerPause,
	IconUsers,
	IconPercentage,
	IconUser,
	IconUserPlus,
	IconUserX,
	IconUserCheck,
	IconUserMinus,
	IconPhoneCall,
	IconPhone,
	IconBrandX,
	IconChartPie,
	IconPin,
	IconPlayerPlay,
	IconPlus,
	IconCirclePlus,
	IconSquarePlus,
	IconPower,
	IconTags,
	IconPrinter,
	IconPuzzle,
	IconHelp,
	IconCircle,
	IconCircleDot,
	IconDeviceCctv,
	IconArrowForwardUp,
	IconRefresh,
	IconRefreshDot,
	IconDeviceFloppy,
	IconScissors,
	IconSearch,
	IconShare,
	IconShieldOff,
	IconShield,
	IconShieldCheck,
	IconShoppingBag,
	IconShoppingCart,
	IconArrowsShuffle,
	IconPlayerSkipBack,
	IconPlayerSkipForward,
	IconSlash,
	IconDeviceMobile,
	IconMoodSmile,
	IconVolume,
	IconVolume2,
	IconVolume3,
	IconVolumeOff,
	IconSquare,
	IconStar,
	IconPlayerStop,
	IconStopwatch,
	IconSun,
	IconArrowsExchange,
	IconTextCaption,
	IconThermometer,
	IconThumbDown,
	IconThumbUp,
	IconTrash,
	IconTrendingDown,
	IconTrendingUp,
	IconDeviceTv,
	IconUmbrella,
	IconArrowBackUp,
	IconUpload,
	IconVideo,
	IconWifi,
	IconBrandWindows,
	IconBrandLinkedinFilled,
	IconBrandFacebookFilled,
	IconBrandGithubFilled,
	IconBrandGoogleFilled,
	IconBrandXFilled
} from 'angular-tabler-icons/icons';

const icons = {
	'activity': IconActivity,
	'activity-outline': IconActivity,
	'alert-circle-outline': IconAlertCircle,
	'alert-triangle-outline': IconAlertTriangle,
	'angle-left': IconChevronLeft,
	'angle-right': IconChevronRight,
	'archive': IconArchive,
	'archive-outline': IconArchive,
	'arrow-back': IconArrowLeft,
	'arrow-back-outline': IconArrowLeft,
	'arrow-circle-up-outline': IconArrowUpCircle,
	'arrow-downward-outline': IconArrowDown,
	'arrow-forward-outline': IconArrowRight,
	'arrowhead-down-outline': IconChevronDown,
	'arrowhead-left-outline': IconChevronLeft,
	'arrowhead-right-outline': IconChevronRight,
	'arrow-ios-back': IconChevronLeft,
	'arrow-ios-back-outline': IconChevronLeft,
	'arrow-ios-downward': IconChevronDown,
	'arrow-ios-downward-outline': IconChevronDown,
	'arrow-ios-forward': IconChevronRight,
	'arrow-ios-forward-outline': IconChevronRight,
	'arrow-left': IconArrowLeft,
	'arrow-left-outline': IconArrowLeft,
	'arrow-right': IconArrowRight,
	'arrow-right-outline': IconArrowRight,
	'arrow-upward-outline': IconArrowUp,
	'at-outline': IconAt,
	'attach-2': IconPaperclip,
	'attach-2-outline': IconPaperclip,
	'attach-outline': IconPaperclip,
	'award-outline': IconAward,
	'bar-chart-2-outline': IconChartBar,
	'bar-chart-outline': IconChartBar,
	'bell-outline': IconBell,
	'book-open-outline': IconBook,
	'book-outline': IconBook,
	'briefcase-outline': IconBriefcase,
	'browser-outline': IconBrowser,
	'bulb-outline': IconBulb,
	'calendar': IconCalendar,
	'calendar-outline': IconCalendar,
	'camera-outline': IconCamera,
	'car-outline': IconCar,
	'card-outline': IconCreditCard,
	'cast-outline': IconCast,
	'check-circle': IconCircleCheck,
	'checkmark-circle': IconCircleCheck,
	'checkmark-circle-2': IconCircleCheck,
	'checkmark-circle-2-outline': IconCircleCheck,
	'checkmark-circle-outline': IconCircleCheck,
	'checkmark-outline': IconCheck,
	'checkmark-square-2-outline': IconSquareCheck,
	'checkmark-square-outline': IconSquareCheck,
	'chevron-down': IconChevronDown,
	'chevron-down-outline': IconChevronDown,
	'chevron-left': IconChevronLeft,
	'chevron-left-outline': IconChevronLeft,
	'chevron-right': IconChevronRight,
	'chevron-right-outline': IconChevronRight,
	'chevron-up': IconChevronUp,
	'chevron-up-outline': IconChevronUp,
	'clock': IconClock,
	'clock-outline': IconClock,
	'close': IconX,
	'close-circle': IconCircleX,
	'close-circle-outline': IconCircleX,
	'close-outline': IconX,
	'close-square-outline': IconSquareX,
	'cloud-download-outline': IconCloudDownload,
	'cloud-upload-outline': IconCloudUpload,
	'code-outline': IconCode,
	'cog': IconSettings,
	'cog-outline': IconSettings,
	'collapse-outline': IconArrowsMinimize,
	'color-palette-outline': IconPalette,
	'compass-outline': IconCompass,
	'copy': IconCopy,
	'copy-outline': IconCopy,
	'corner-down-right-outline': IconCornerDownRight,
	'cpu-outline': IconCpu,
	'credit-card-outline': IconCreditCard,
	'cube-outline': IconCube,
	'diagonal-arrow-right-up-outline': IconArrowUpRight,
	'done-all-outline': IconChecks,
	'download': IconDownload,
	'download-outline': IconDownload,
	'edit': IconEdit,
	'edit-2': IconEdit,
	'edit-2-outline': IconEdit,
	'edit-outline': IconEdit,
	'email': IconMail,
	'email-outline': IconMail,
	'expand-outline': IconMaximize,
	'external-link-outline': IconExternalLink,
	'eye': IconEye,
	'eye-off': IconEyeOff,
	'eye-off-2-outline': IconEyeOff,
	'eye-off-outline': IconEyeOff,
	'eye-outline': IconEye,
	'facebook': IconBrandFacebookFilled,
	'facebook-outline': IconBrandFacebook,
	'file': IconFile,
	'file-add-outline': IconFilePlus,
	'file-outline': IconFile,
	'file-text': IconFileText,
	'file-text-outline': IconFileText,
	'film-outline': IconMovie,
	'flag-outline': IconFlag,
	'flash-outline': IconBolt,
	'flip-2-outline': IconRotate2,
	'folder': IconFolder,
	'folder-add-outline': IconFolderPlus,
	'folder-outline': IconFolder,
	'funnel-outline': IconFilter,
	'gift-outline': IconGift,
	'git-branch-outline': IconGitBranch,
	'git-commit-outline': IconGitCommit,
	'github': IconBrandGithubFilled,
	'github-outline': IconBrandGithub,
	'globe-2-outline': IconGlobe,
	'globe-outline': IconGlobe,
	'google': IconBrandGoogleFilled,
	'google-outline': IconBrandGoogle,
	'grid': IconGridDots,
	'grid-outline': IconGridDots,
	'grid-view': IconGridDots,
	'hard-drive-outline': IconServer,
	'hash-outline': IconHash,
	'heart-outline': IconHeart,
	'home-outline': IconHome,
	'image-off-outline': IconPhotoOff,
	'image-outline': IconPhoto,
	'inbox-outline': IconInbox,
	'info': IconInfoCircle,
	'info-circle-outline': IconInfoCircle,
	'info-outline': IconInfoCircle,
	'keypad-outline': IconKeyboard,
	'layers': IconStack2,
	'layers-outline': IconStack2,
	'layout-outline': IconLayout,
	'link-2-outline': IconLink,
	'link-outline': IconLink,
	'linkedin': IconBrandLinkedinFilled,
	'linkedin-outline': IconBrandLinkedin,
	'list': IconList,
	'list-outline': IconList,
	'loader-outline': IconLoader,
	'lock-outline': IconLock,
	'log-in': IconLogin,
	'log-in-outline': IconLogin,
	'log-out-outline': IconLogout,
	'map-outline': IconMap,
	'menu-2-outline': IconMenu2,
	'menu-arrow-outline': IconMenuOrder,
	'menu-outline': IconMenu2,
	'message-circle-outline': IconMessageCircle,
	'message-square-outline': IconMessage,
	'mic-outline': IconMicrophone,
	'microsoft': IconBrandWindowsFilled,
	'microsoft-outline': IconBrandWindows,
	'minus': IconMinus,
	'minus-circle': IconCircleMinus,
	'minus-circle-outline': IconCircleMinus,
	'minus-outline': IconMinus,
	'minus-square-outline': IconSquareMinus,
	'monitor-outline': IconDeviceDesktop,
	'moon-outline': IconMoon,
	'more-horizontal-outline': IconDots,
	'more-vertical-outline': IconDotsVertical,
	'move-outline': IconArrowsMove,
	'navigation-2-outline': IconNavigation,
	'npm': IconBrandNpm,
	'npm-outline': IconBrandNpm,
	'options-2-outline': IconAdjustmentsHorizontal,
	'options-outline': IconAdjustmentsHorizontal,
	'pantone-outline': IconPalette,
	'paper-plane-outline': IconSend,
	'pause': IconPlayerPause,
	'pause-circle-outline': IconPlayerPause,
	'people-outline': IconUsers,
	'percent': IconPercentage,
	'percent-outline': IconPercentage,
	'person': IconUser,
	'person-add-outline': IconUserPlus,
	'person-delete-outline': IconUserX,
	'person-done-outline': IconUserCheck,
	'person-outline': IconUser,
	'person-remove-outline': IconUserMinus,
	'phone-call-outline': IconPhoneCall,
	'phone-outline': IconPhone,
	'pie-chart-outline': IconChartPie,
	'pin-outline': IconPin,
	'play': IconPlayerPlay,
	'play-circle-outline': IconPlayerPlay,
	'plus': IconPlus,
	'plus-circle': IconCirclePlus,
	'plus-circle-outline': IconCirclePlus,
	'plus-outline': IconPlus,
	'plus-square-outline': IconSquarePlus,
	'power-outline': IconPower,
	'pricetags-outline': IconTags,
	'printer-outline': IconPrinter,
	'puzzle-outline': IconPuzzle,
	'question-mark-circle-outline': IconHelp,
	'radio-button-off-outline': IconCircle,
	'radio-button-on-outline': IconCircleDot,
	'recording-outline': IconDeviceCctv,
	'redo-alt': IconArrowForwardUp,
	'refresh-outline': IconRefresh,
	'save': IconDeviceFloppy,
	'save-outline': IconDeviceFloppy,
	'scissors-outline': IconScissors,
	'search': IconSearch,
	'search-outline': IconSearch,
	'settings-2-outline': IconSettings,
	'settings-outline': IconSettings,
	'share-outline': IconShare,
	'shield-checkmark-outline': IconShieldCheck,
	'shield-off-outline': IconShieldOff,
	'shield-outline': IconShield,
	'shopping-bag-outline': IconShoppingBag,
	'shopping-cart-outline': IconShoppingCart,
	'shuffle-2-outline': IconArrowsShuffle,
	'skip-back-outline': IconPlayerSkipBack,
	'skip-forward-outline': IconPlayerSkipForward,
	'slash-outline': IconSlash,
	'smartphone-outline': IconDeviceMobile,
	'smiling-face-outline': IconMoodSmile,
	'speaker-outline': IconVolume,
	'square-outline': IconSquare,
	'star': IconStar,
	'star-outline': IconStar,
	'stop-circle-outline': IconPlayerStop,
	'stopwatch': IconStopwatch,
	'sun-outline': IconSun,
	'swap': IconArrowsExchange,
	'swap-outline': IconArrowsExchange,
	'sync-alt': IconRefreshDot,
	'sync-outline': IconRefresh,
	'text-outline': IconTextCaption,
	'thermometer-outline': IconThermometer,
	'thumbs-down-outline': IconThumbDown,
	'thumbs-up-outline': IconThumbUp,
	'time-outline': IconClock,
	'trash': IconTrash,
	'trash-2': IconTrash,
	'trash-2-outline': IconTrash,
	'trash-outline': IconTrash,
	'trending-down-outline': IconTrendingDown,
	'trending-up-outline': IconTrendingUp,
	'tv-outline': IconDeviceTv,
	'twitter': IconBrandXFilled,
	'twitter-outline': IconBrandX,
	'umbrella-outline': IconUmbrella,
	'undo-outline': IconArrowBackUp,
	'unlock-outline': IconLockOpen,
	'upload-outline': IconUpload,
	'video-outline': IconVideo,
	'volume-down-outline': IconVolume2,
	'volume-mute-outline': IconVolume3,
	'volume-off-outline': IconVolumeOff,
	'volume-up-outline': IconVolume,
	'wifi-outline': IconWifi
};

@NgModule()
export class NbTablerIconsModule {
	constructor(private iconLibraries: NbIconLibraries) {
		this.registerTablerPack();
	}

	registerTablerPack() {
		this.iconLibraries.registerSvgPack('eva', icons);
		this.iconLibraries.setDefaultPack('eva');
	}
}
